<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hfwu_redirects"
 *
 * Auto generated by Extension Builder 2016-04-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'HFWU Redirects',
	'description' => '',
	'category' => 'module',
	'author' => 'Uwe Beck, Manfred Mirsch',
	'author_email' => 'mmirsch@hs-esslingen.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);